name: Bug Report
description: Report a bug in design-audit-cli
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below to help us reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: design-audit-cli version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "v20.x"
    validations:
      required: true

  - type: input
    id: playwright-cli
    attributes:
      label: playwright-cli version
      placeholder: "1.50.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 14.2 / Ubuntu 22.04 / Windows 11"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL that was audited
      placeholder: "http://localhost:3000 (or 'localhost' if you'd prefer not to share)"

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. Include the command you ran.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Full error output
      render: shell
